import '../engine/city_resolver.dart';

/// Türkiye illerinin kara sınırı komşuları — çevre önerisi için.
///
/// Anahtarlar [KamiCityResolver.normalize] ile eşleşir.
abstract final class KamiCityNeighbors {
  /// Komşu iller (display adlarıyla). Normalize edilerek aranır.
  static const Map<String, List<String>> _raw = {
    'Adana': ['Mersin', 'Hatay', 'Osmaniye', 'Kahramanmaras', 'Kayseri', 'Nigde'],
    'Adiyaman': ['Malatya', 'Kahramanmaras', 'Gaziantep', 'Sanliurfa', 'Diyarbakir'],
    'Afyonkarahisar': [
      'Eskisehir',
      'Kutahya',
      'Usak',
      'Denizli',
      'Burdur',
      'Isparta',
      'Konya',
    ],
    'Agri': ['Erzurum', 'Kars', 'Igdir', 'Van', 'Bitlis', 'Mus'],
    'Aksaray': ['Ankara', 'Kirsehir', 'Nevsehir', 'Nigde', 'Konya', 'Kayseri'],
    'Amasya': ['Samsun', 'Tokat', 'Yozgat', 'Corum'],
    'Ankara': [
      'Cankiri',
      'Kirikkale',
      'Kirsehir',
      'Aksaray',
      'Konya',
      'Eskisehir',
      'Bolu',
    ],
    'Antalya': ['Mugla', 'Burdur', 'Isparta', 'Konya', 'Karaman', 'Mersin'],
    'Ardahan': ['Artvin', 'Erzurum', 'Kars'],
    'Artvin': ['Rize', 'Erzurum', 'Ardahan'],
    'Aydin': ['Izmir', 'Manisa', 'Denizli', 'Mugla'],
    'Balikesir': ['Canakkale', 'Bursa', 'Kutahya', 'Manisa', 'Izmir'],
    'Bartin': ['Zonguldak', 'Kastamonu', 'Karabuk'],
    'Batman': ['Diyarbakir', 'Mus', 'Bitlis', 'Siirt', 'Mardin'],
    'Bayburt': ['Trabzon', 'Gumushane', 'Erzurum', 'Erzincan', 'Rize'],
    'Bilecik': ['Sakarya', 'Bursa', 'Kutahya', 'Eskisehir', 'Bolu'],
    'Bingol': ['Erzurum', 'Mus', 'Diyarbakir', 'Elazig', 'Tunceli', 'Erzincan'],
    'Bitlis': ['Mus', 'Agri', 'Van', 'Siirt', 'Batman'],
    'Bolu': [
      'Zonguldak',
      'Karabuk',
      'Cankiri',
      'Ankara',
      'Eskisehir',
      'Bilecik',
      'Sakarya',
      'Duzce',
    ],
    'Burdur': ['Isparta', 'Antalya', 'Mugla', 'Denizli', 'Afyonkarahisar'],
    'Bursa': ['Yalova', 'Kocaeli', 'Sakarya', 'Bilecik', 'Kutahya', 'Balikesir'],
    'Canakkale': ['Tekirdag', 'Balikesir', 'Edirne'],
    'Cankiri': ['Kastamonu', 'Corum', 'Kirikkale', 'Ankara', 'Bolu', 'Karabuk'],
    'Corum': ['Amasya', 'Samsun', 'Sinop', 'Kastamonu', 'Cankiri', 'Kirikkale', 'Yozgat'],
    'Denizli': [
      'Afyonkarahisar',
      'Usak',
      'Manisa',
      'Aydin',
      'Mugla',
      'Burdur',
      'Isparta',
    ],
    'Diyarbakir': [
      'Elazig',
      'Bingol',
      'Mus',
      'Batman',
      'Mardin',
      'Sanliurfa',
      'Adiyaman',
      'Malatya',
    ],
    'Duzce': ['Zonguldak', 'Bolu', 'Sakarya'],
    'Edirne': ['Kirklareli', 'Tekirdag', 'Canakkale'],
    'Elazig': ['Tunceli', 'Bingol', 'Diyarbakir', 'Malatya', 'Erzincan'],
    'Erzincan': [
      'Gumushane',
      'Bayburt',
      'Erzurum',
      'Bingol',
      'Tunceli',
      'Elazig',
      'Malatya',
      'Sivas',
    ],
    'Erzurum': [
      'Rize',
      'Artvin',
      'Ardahan',
      'Kars',
      'Agri',
      'Mus',
      'Bingol',
      'Erzincan',
      'Bayburt',
    ],
    'Eskisehir': [
      'Bilecik',
      'Kutahya',
      'Afyonkarahisar',
      'Konya',
      'Ankara',
      'Bolu',
    ],
    'Gaziantep': ['Kahramanmaras', 'Osmaniye', 'Hatay', 'Kilis', 'Sanliurfa', 'Adiyaman'],
    'Giresun': ['Trabzon', 'Gumushane', 'Erzincan', 'Sivas', 'Ordu'],
    'Gumushane': ['Trabzon', 'Bayburt', 'Erzincan', 'Giresun'],
    'Hakkari': ['Van', 'Sirnak'],
    'Hatay': ['Adana', 'Osmaniye', 'Gaziantep'],
    'Igdir': ['Kars', 'Agri'],
    'Isparta': ['Afyonkarahisar', 'Konya', 'Antalya', 'Burdur', 'Denizli'],
    'Istanbul': ['Tekirdag', 'Kocaeli'],
    'Izmir': ['Balikesir', 'Manisa', 'Aydin'],
    'Kahramanmaras': [
      'Sivas',
      'Kayseri',
      'Adana',
      'Osmaniye',
      'Gaziantep',
      'Adiyaman',
      'Malatya',
    ],
    'Karabuk': ['Zonguldak', 'Bartin', 'Kastamonu', 'Cankiri', 'Bolu'],
    'Karaman': ['Konya', 'Mersin', 'Antalya'],
    'Kars': ['Ardahan', 'Erzurum', 'Agri', 'Igdir'],
    'Kastamonu': ['Sinop', 'Corum', 'Cankiri', 'Karabuk', 'Bartin'],
    'Kayseri': [
      'Sivas',
      'Yozgat',
      'Nevsehir',
      'Nigde',
      'Adana',
      'Kahramanmaras',
      'Malatya',
      'Kirsehir',
      'Aksaray',
    ],
    'Kilis': ['Gaziantep', 'Hatay'],
    'Kirikkale': ['Corum', 'Yozgat', 'Kirsehir', 'Ankara', 'Cankiri'],
    'Kirklareli': ['Edirne', 'Tekirdag'],
    'Kirsehir': ['Kirikkale', 'Yozgat', 'Nevsehir', 'Aksaray', 'Ankara', 'Kayseri'],
    'Kocaeli': ['Istanbul', 'Yalova', 'Bursa', 'Sakarya'],
    'Konya': [
      'Ankara',
      'Aksaray',
      'Nigde',
      'Mersin',
      'Karaman',
      'Antalya',
      'Isparta',
      'Afyonkarahisar',
      'Eskisehir',
    ],
    'Kutahya': [
      'Bursa',
      'Bilecik',
      'Eskisehir',
      'Afyonkarahisar',
      'Usak',
      'Manisa',
      'Balikesir',
    ],
    'Malatya': [
      'Sivas',
      'Erzincan',
      'Elazig',
      'Diyarbakir',
      'Adiyaman',
      'Kahramanmaras',
      'Kayseri',
    ],
    'Manisa': ['Balikesir', 'Kutahya', 'Usak', 'Denizli', 'Aydin', 'Izmir'],
    'Mardin': ['Diyarbakir', 'Batman', 'Siirt', 'Sirnak', 'Sanliurfa'],
    'Mersin': ['Antalya', 'Karaman', 'Konya', 'Nigde', 'Adana'],
    'Mugla': ['Aydin', 'Denizli', 'Burdur', 'Antalya'],
    'Mus': ['Erzurum', 'Agri', 'Bitlis', 'Batman', 'Diyarbakir', 'Bingol'],
    'Nevsehir': ['Kirsehir', 'Yozgat', 'Kayseri', 'Nigde', 'Aksaray'],
    'Nigde': ['Nevsehir', 'Kayseri', 'Adana', 'Mersin', 'Konya', 'Aksaray'],
    'Ordu': ['Samsun', 'Tokat', 'Sivas', 'Giresun'],
    'Osmaniye': ['Adana', 'Kahramanmaras', 'Gaziantep', 'Hatay'],
    'Rize': ['Artvin', 'Erzurum', 'Bayburt', 'Trabzon'],
    'Sakarya': ['Kocaeli', 'Bursa', 'Bilecik', 'Bolu', 'Duzce'],
    'Samsun': ['Sinop', 'Corum', 'Amasya', 'Tokat', 'Ordu'],
    'Sanliurfa': ['Gaziantep', 'Adiyaman', 'Diyarbakir', 'Mardin'],
    'Siirt': ['Bitlis', 'Van', 'Hakkari', 'Sirnak', 'Mardin', 'Batman'],
    'Sinop': ['Kastamonu', 'Corum', 'Samsun'],
    'Sirnak': ['Mardin', 'Siirt', 'Hakkari'],
    'Sivas': [
      'Tokat',
      'Ordu',
      'Giresun',
      'Erzincan',
      'Malatya',
      'Kahramanmaras',
      'Kayseri',
      'Yozgat',
    ],
    'Tekirdag': ['Kirklareli', 'Edirne', 'Canakkale', 'Istanbul'],
    'Tokat': ['Amasya', 'Samsun', 'Ordu', 'Sivas', 'Yozgat'],
    'Trabzon': ['Rize', 'Bayburt', 'Gumushane', 'Giresun'],
    'Tunceli': ['Erzincan', 'Bingol', 'Elazig'],
    'Usak': ['Kutahya', 'Afyonkarahisar', 'Denizli', 'Manisa'],
    'Van': ['Agri', 'Bitlis', 'Siirt', 'Hakkari', 'Mus'],
    'Yalova': ['Kocaeli', 'Bursa'],
    'Yozgat': [
      'Corum',
      'Amasya',
      'Tokat',
      'Sivas',
      'Kayseri',
      'Nevsehir',
      'Kirsehir',
      'Kirikkale',
    ],
    'Zonguldak': ['Bartin', 'Karabuk', 'Bolu', 'Duzce'],
  };

  /// [homeCity] için komşu il display adları.
  static Set<String> neighborsOf(String homeCity) {
    final key = KamiCityResolver.normalize(homeCity);
    for (final e in _raw.entries) {
      if (KamiCityResolver.normalize(e.key) == key) {
        return e.value.toSet();
      }
    }
    return {};
  }

  static bool isNeighbor(String homeCity, String otherCity) {
    final nOther = KamiCityResolver.normalize(otherCity);
    for (final n in neighborsOf(homeCity)) {
      if (KamiCityResolver.normalize(n) == nOther) return true;
    }
    return false;
  }
}
